##################################################
### Install symfony
- name: Download Symfony Installer
  get_url:
    url="{{ symfony_url }}"
    dest="{{ symfony_dest }}"
    mode=777

##################################################
### Configure symfony project
- name: Check if project already exists
  stat: path="/vagrant/{{ projectname }}"
  register: stat_project

- name: Create project
  shell: cd /vagrant && symfony new {{ projectname }} {{ symfony_version }}
  when: stat_project.stat.exists == false

##################################################
### Configure nginx

- name: Copy new virtual hosts file.
  template:
    src=nginx_project_vhost.skel
    dest=/etc/nginx/sites-available/{{ projectname }}

- name: Enable new virtual hosts file.
  file:
    src=/etc/nginx/sites-available/{{ projectname }}
    dest=/etc/nginx/sites-enabled/{{ projectname }}
    state=link
  notify:
   - restart nginx