##################################################
# Install and configure PHP
- name: Add apt key for Debian
  apt_key: url=https://packages.sury.org/php/apt.gpg state=present

- name: Add repository for Debian
  apt_repository: repo="deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main" state=present

- name: Update apt
  apt: update_cache=yes

- name: Install PHP Packages
  apt: name={{ item }} state=present
  with_items:
    - php7.1
    - php7.1-fpm
    - php7.1-mysql
    - php7.1-mcrypt
    - php7.1-cli
    - php7.1-curl
    - php7.1-gd
    - php7.1-intl
    - php7.1-json
    - php7.1-mbstring
    - php7.1-opcache
    - php7.1-readline
    - php7.1-xml
    - php7.1-xsl
    - php7.1-zip
    - php-common

- name: Copy PHP-FPM config
  template:
    src=www.conf
    dest=/etc/php/7.1/fpm/pool.d/www.conf

- lineinfile:
    dest: /etc/php/7.1/fpm/php.ini
    regexp: '^;date.timezone'
    line: 'date.timezone = "Europe/Berlin"'

- name: Restart PHP-FPM
  service: name=php7.1-fpm state=restarted

##################################################
# Install Composer
- name: Install Composer globally
  shell: curl -sS https://getcomposer.org/installer | /usr/bin/php && /bin/mv -f composer.phar {{ composer_path }} creates={{ composer_path }}
