##################################################
# Install and configure PHP
- name: Add apt key for Debian
  apt_key: url={{ repo_keyserver_url }} state=present

- name: Add repository for Debian
  apt_repository: repo="deb {{ repo_server_url }} {{ ansible_distribution_release }} main" state=present update_cache=yes

- name: Install PHP Packages
  apt: name={{ item }} state=present
  with_items:
    - php{{ php_version }}
    - php{{ php_version }}-fpm
    - php{{ php_version }}-mysql
    - php{{ php_version }}-mcrypt
    - php{{ php_version }}-cli
    - php{{ php_version }}-curl
    - php{{ php_version }}-gd
    - php{{ php_version }}-intl
    - php{{ php_version }}-json
    - php{{ php_version }}-mbstring
    - php{{ php_version }}-opcache
    - php{{ php_version }}-readline
    - php{{ php_version }}-xml
    - php{{ php_version }}-xsl
    - php{{ php_version }}-zip
    - php{{ php_version }}-bz2
    - php-common

- name: Copy PHP-FPM config
  template:
    src=www.conf
    dest=/etc/php/{{ php_version }}/fpm/pool.d/www.conf

- lineinfile:
    dest=/etc/php/{{ php_version }}/fpm/php.ini
    regexp='^;date.timezone'
    line='date.timezone = "Europe/Berlin"'

- name: Restart PHP-FPM
  service: name=php{{ php_version }}-fpm state=restarted

##################################################
# Install Composer
- name: Download Composer
  shell: curl -sS https://getcomposer.org/installer | /usr/bin/php && /bin/mv -f composer.phar {{ composer_path }} creates={{ composer_path }}
