##################################################
### Install nodejs
- name: Add repository for Debian
  shell: "curl -sL {{ repo_server_url }} | bash -"

- name: Install Nodejs
  apt: name={{ item }} state=latest
  with_items:
    - nodejs
